### ISSUE TITLE
Rebuild deployment?

### ISSUE THREAD

**Issue by Souliboi** [StrataWM/stratawm.github.io#1]
Currently the deployment seems to still be using the old link for getting started?
![image](https://github.com/StrataWM/stratawm.github.io/assets/106060704/7534c16c-cad9-4c38-99d1-7880a49581b7)
even though it seems to have already been fixed in the code [here](https://github.com/StrataWM/stratawm.github.io/blob/edb2a486ea92e152079a16194a1eddf62ae73620/src/Components/routes/Home.svelte#L24) at least from trying to piece my way through this

**Comment by anantnrg** [comment]
I'll look into this but currently I dont have access to my PC so it'll take some time. Thanks for pointing it out thought!

**Comment by Souliboi** [comment]
Ah alright, thanks in advance!

**Comment by anantnrg** [comment]
Fixed it!
